apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-capstone-app
  template:
    metadata:
      labels:
        app: sample-capstone-app
    spec:
      containers:
        - name: back-end
          image: gsindhwani/sample-capstone-app
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: sample-capstone-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080