apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
  labels:
    app: capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project
  template:
    metadata:
      labels:
        app: capstone-project
    spec:
      containers:
        - name: back-end
          image: longbui-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "4Gi"   
              cpu: "2"       
            limits:
              memory: "4Gi"
              cpu: "2"

---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080