apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: longbui-api:v1.0.0
  template:
    metadata:
      labels:
        app: longbui-api:v1.0.0
    spec:
      containers:
        - name: myapp-container
          image: longtony/longbui-api:v1.0.0
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: longbui-api:v1.0.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080