apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hello-cluster
  region: us-east-1
iam:
  withOIDC: false
  serviceRoleARN: arn:aws:iam::717010040964:role/myEKSClusterRole
managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    iam:
      instanceRoleARN: arn:aws:iam::717010040964:instance-profile/myEKSWorkerNodeRole