version: 2.1

orbs:
    aws-cli: circleci/aws-cli@4.1.2

jobs:
  linting-code:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }} # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            . ~/.devops/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ~/.devops
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: # run lint!
          name: run lint
          command: |
            . ~/.devops/bin/activate
            make lint

  build_deploy_docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create docker image
          command: |
            docker build -t longbui-api .

  publish_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create ECR and publish docker image to ECR
          command: bash bash_script/create_ecr.sh

  create_kubernets_cluster:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install kubernetes utilities
          command: make install_kubernetes_utility
      - run:
          name: Create cluster
          command: bash bash_scipt/create_cluster.sh
              
workflows:
  default:
    jobs:
      - linting-code
      - build_deploy_docker:
          requires: [linting-code]
      - publish_docker_image:
          requires: [build_deploy_docker]
      - create_kubernets_cluster:
          requires: [publish_docker_image]